[package]
name = "aoko"
version = "0.1.12"
authors = ["hzqd <hzqelf@yeah.net>"]
edition = "2018"
description = "A Rust extension library."
repository = "https://github.com/hzqd/aoko"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"